version: 2.0

jobs:
    build:
        branches:
          only:
            - source
        docker:
            - image: felicianotech/docker-hugo:latest
        working_directory: ~/hemifuture.github.io
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "3b:65:cf:94:9b:a7:b0:5c:48:86:7e:dd:00:eb:b2:97"
            - checkout
            - run:
                name: Get current site
                working_directory: ~/
                command: git clone -b master git@github.com:hemifuture/hemifuture.github.io.git public
            - run:
                name: Generate site
                working_directory: ~/hemifuture.github.io
                command: HUGO_ENV=production hugo -d ~/public
            - deploy:
                name: Deploy to Github Pages
                working_directory: ~/public
                command: |
                    git config credential.helper 'cache --timeout=120'
                    git config user.email "dyzdyz010@gmail.com"
                    git config user.name "Deployment Bot"
                    git add .
                    git commit --allow-empty -m "Trigger deployment"
                    git push -q git@github.com:hemifuture/hemifuture.github.io.git master